### PR TITLE
Add caching to pre-commit job

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
hmmmph it's slower than not cached. seems azure pipelines sends every individual file :/ it would probably be faster if it were zipped / unzipped

**Comment by asottile** [comment]
turns out it is broken for other reasons making this unusable for now:
- https://github.com/microsoft/azure-pipelines-tasks/issues/11350
- https://github.com/microsoft/azure-pipelines-tasks/issues/11351

**Comment by ssbarnea** [comment]
I guess they still need to discover iron age tools like rsync or NFS volumes? Are you on github actions 2.0 beta?

**Comment by asottile** [comment]
sweet, they switched to `tar` internally so now it's fast again without extra code

**Pull request merged**
