### PR TITLE
Add python 2.6

### PR DESCRIPTION
**Pull request by sloria**
For the poor saps like me who are stuck with projects that
support it.

### CODE REVIEW

**Comment by asottile** [comment]
I don't think this is sufficient because neither pip nor tox nor virtualenv support python2.6

**Comment by asottile** [comment]
btw, hope someone is paying you $$$, it's 2109 gotta let python2.6 go :P

**Comment by sloria** [comment]
Hm, tox still seems to work fine with this setup.

https://github.com/marshmallow-code/marshmallow/blob/72c6a88a9edc99247f45641073b51cdeec68c977/azure-pipelines.yml#L15-L19

image


yeah...looking forward to giving python 2 the Marie Kondo treatment soon...

**Comment by asottile** [comment]
hehehe, take a look at your log: https://dev.azure.com/sloria/sloria/_build/results?buildId=21

```
py26 create: /home/vsts/work/1/s/.tox/py26

[...]

py26 run-test: commands[0] | pytest --ignore=tests/test_py3/
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-5.0.0, py-1.8.0, pluggy-0.12.0 -- /home/vsts/work/1/s/.tox/py26/bin/python
```

**Comment by sloria** [comment]
ah s, good catch. K, will look into it when I have some time.

**Comment by asottile** [comment]
closing since this doesn't / can't work without a lot of hacks

**Comment by sloria** [comment]
Fair enough. I'm hoping https://github.com/marshmallow-code/marshmallow/issues/1274 will be uncontroversial 😅

**Pull request closed without merging**
